/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vizualizer.periodictable;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import visualizer.database.FileDatabase;
import visualizer.model.AdvancedElement;

/**
 *
 * @author Anytram
 */
public class PeriodicPanel extends javax.swing.JPanel {

    private FileDatabase database;
    private AdvancedElement element;
    private String summary;

    /**
     * Creates new form PeriodicPanel
     */
    public PeriodicPanel() throws IOException, URISyntaxException {
        initComponents();
        database = FileDatabase.getInstance();
        initComponents();
        jComboBox1.setModel(new DefaultComboBoxModel<>(database.getAllNames()));
        jTextArea1.setFont(new Font("Century Gothic", Font.PLAIN, 20));
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
    }

    public void setSelectedAtom(String selectedAtom) {
        summary = database.findByName(selectedAtom).getSummary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new JComboBox<>();
        periodicTable1 = new PeriodicTable();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();

        FormListener formListener = new FormListener();

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(formListener);

        GroupLayout periodicTable1Layout = new GroupLayout(periodicTable1);
        periodicTable1.setLayout(periodicTable1Layout);
        periodicTable1Layout.setHorizontalGroup(periodicTable1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1175, Short.MAX_VALUE)
        );
        periodicTable1Layout.setVerticalGroup(periodicTable1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(periodicTable1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(periodicTable1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == jComboBox1) {
                PeriodicPanel.this.jComboBox1ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        setSelectedAtom((String) jComboBox1.getSelectedItem());
        jTextArea1.setText(summary);
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JComboBox<String> jComboBox1;
    private JScrollPane jScrollPane1;
    private JTextArea jTextArea1;
    private PeriodicTable periodicTable1;
    // End of variables declaration//GEN-END:variables

}
